name: Test Secret

on:
  push:
  workflow_dispatch:

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          # cache: 'npm'                   # Caching is not available in nektos/act Medium images. Uncomment when using in live actions.
      
      - name: Install
        run: |
          npm ci
      
      - name: Test
        env:
          HELLO_WORLD: 'Hello from GitHub Actions in Open'
          HELLO_SECRET: '${{ secrets.HELLO_SECRET_IN_DASHBOARD }}'
        run: |
          npm test
